-- =====================================================================
-- SEED — catálogo de exercícios
-- =====================================================================
-- Gerado a partir de 02_catalogo_exercicios.csv (163 exercícios).
-- NÃO editar à mão: reexecutar `npm run seed:gerar` depois de mudar o CSV.
--
-- Idempotente: `on conflict (id) do update` permite reaplicar o seed
-- sobre um banco já populado sem quebrar as FKs de sessao_exercicios.
-- =====================================================================

insert into public.exercicios
  (id, nome, grupo_primario, grupos_secundarios, padrao_movimento,
   equipamento, incremento_kg, unilateral, medida, comum)
values
  (1, 'Abdução miniband', 'abdutores', array['glúteo']::grupo_muscular[], 'isolamento de perna', 'elástico', null, false, 'reps', 3),
  (2, 'Abdução na máquina', 'abdutores', '{}'::grupo_muscular[], 'isolamento de perna', 'máquina', 5.0, false, 'reps', 1),
  (3, 'Abdução na polia', 'abdutores', '{}'::grupo_muscular[], 'isolamento de perna', 'polia', 2.5, true, 'reps', 2),
  (4, 'Monster Walk', 'abdutores', array['glúteo']::grupo_muscular[], 'isolamento de perna', 'elástico', null, false, 'reps', 3),
  (5, 'Dead Bug', 'abdômen', '{}'::grupo_muscular[], 'antiextensão', 'peso corporal', null, false, 'reps', 2),
  (6, 'Dragon Flag', 'abdômen', '{}'::grupo_muscular[], 'antiextensão', 'peso corporal', null, false, 'reps', 3),
  (7, 'Hollow Hold', 'abdômen', '{}'::grupo_muscular[], 'antiextensão', 'peso corporal', null, false, 'tempo', 3),
  (8, 'Mountain Climbers', 'abdômen', '{}'::grupo_muscular[], 'antiextensão', 'peso corporal', null, false, 'tempo', 2),
  (9, 'Prancha isométrica', 'abdômen', array['lombar']::grupo_muscular[], 'antiextensão', 'peso corporal', null, false, 'tempo', 1),
  (10, 'Prancha lateral', 'abdômen', '{}'::grupo_muscular[], 'antiextensão', 'peso corporal', null, true, 'tempo', 2),
  (11, 'Roda abdominal', 'abdômen', '{}'::grupo_muscular[], 'antiextensão', 'peso corporal', null, false, 'reps', 3),
  (12, 'Abdominal infra no solo', 'abdômen', '{}'::grupo_muscular[], 'flexão de tronco', 'peso corporal', null, false, 'reps', 2),
  (13, 'Abdominal na máquina', 'abdômen', '{}'::grupo_muscular[], 'flexão de tronco', 'máquina', 5.0, false, 'reps', 1),
  (14, 'Abdominal na polia alta', 'abdômen', '{}'::grupo_muscular[], 'flexão de tronco', 'polia', 2.5, false, 'reps', 1),
  (15, 'Abdominal supra no solo', 'abdômen', '{}'::grupo_muscular[], 'flexão de tronco', 'peso corporal', null, false, 'reps', 1),
  (16, 'Elevação de pernas no banco', 'abdômen', '{}'::grupo_muscular[], 'flexão de tronco', 'peso corporal', null, false, 'reps', 2),
  (17, 'Elevação de pernas suspenso', 'abdômen', '{}'::grupo_muscular[], 'flexão de tronco', 'peso corporal', null, false, 'reps', 1),
  (18, 'Toes to Bar', 'abdômen', '{}'::grupo_muscular[], 'flexão de tronco', 'peso corporal', null, false, 'reps', 3),
  (19, 'V-Up', 'abdômen', '{}'::grupo_muscular[], 'flexão de tronco', 'peso corporal', null, false, 'reps', 2),
  (20, 'Abdominal bicicleta', 'abdômen', '{}'::grupo_muscular[], 'rotação', 'peso corporal', null, false, 'reps', 2),
  (21, 'Lenhador na polia', 'abdômen', '{}'::grupo_muscular[], 'rotação', 'polia', 2.5, true, 'reps', 3),
  (22, 'Pallof press na polia', 'abdômen', '{}'::grupo_muscular[], 'rotação', 'polia', 2.5, true, 'reps', 3),
  (23, 'Rotação russa com anilha', 'abdômen', '{}'::grupo_muscular[], 'rotação', 'anilha', 2.5, false, 'reps', 2),
  (24, 'Adução na máquina', 'adutores', '{}'::grupo_muscular[], 'isolamento de perna', 'máquina', 5.0, false, 'reps', 1),
  (25, 'Adução polia', 'adutores', '{}'::grupo_muscular[], 'isolamento de perna', 'polia', 2.5, true, 'reps', 2),
  (26, 'Copenhagen Plank', 'adutores', '{}'::grupo_muscular[], 'isolamento de perna', 'peso corporal', null, true, 'tempo', 3),
  (27, 'Farmer Walk', 'bíceps', array['ombro','abdômen']::grupo_muscular[], 'carregamento', 'halter', 2.0, false, 'tempo', 3),
  (28, 'Rosca de punho', 'bíceps', '{}'::grupo_muscular[], 'isolamento de antebraço', 'halter', 2.0, false, 'reps', 2),
  (29, 'Rosca de punho inversa', 'bíceps', '{}'::grupo_muscular[], 'isolamento de antebraço', 'halter', 2.0, false, 'reps', 2),
  (30, 'Wrist Roller', 'bíceps', '{}'::grupo_muscular[], 'isolamento de antebraço', 'anilha', 2.5, false, 'reps', 3),
  (31, 'Rosca 21', 'bíceps', '{}'::grupo_muscular[], 'isolamento de braço', 'barra', 2.5, false, 'reps', 3),
  (32, 'Rosca Bayesian', 'bíceps', '{}'::grupo_muscular[], 'isolamento de braço', 'polia', 2.5, true, 'reps', 3),
  (33, 'Rosca Drag', 'bíceps', '{}'::grupo_muscular[], 'isolamento de braço', 'barra', 2.5, false, 'reps', 3),
  (34, 'Rosca Scott unilateral', 'bíceps', '{}'::grupo_muscular[], 'isolamento de braço', 'halter', 2.0, true, 'reps', 2),
  (35, 'Rosca Spider', 'bíceps', '{}'::grupo_muscular[], 'isolamento de braço', 'halter', 2.0, false, 'reps', 3),
  (36, 'Rosca alternada com halteres', 'bíceps', '{}'::grupo_muscular[], 'isolamento de braço', 'halter', 2.0, true, 'reps', 1),
  (37, 'Rosca concentrada', 'bíceps', '{}'::grupo_muscular[], 'isolamento de braço', 'halter', 2.0, true, 'reps', 2),
  (38, 'Rosca direta com barra', 'bíceps', '{}'::grupo_muscular[], 'isolamento de braço', 'barra', 2.5, false, 'reps', 1),
  (39, 'Rosca direta com barra W', 'bíceps', '{}'::grupo_muscular[], 'isolamento de braço', 'barra', 2.5, false, 'reps', 2),
  (40, 'Rosca inversa', 'bíceps', '{}'::grupo_muscular[], 'isolamento de braço', 'barra', 2.5, false, 'reps', 2),
  (41, 'Rosca martelo', 'bíceps', '{}'::grupo_muscular[], 'isolamento de braço', 'halter', 2.0, true, 'reps', 1),
  (42, 'Rosca na polia baixa', 'bíceps', '{}'::grupo_muscular[], 'isolamento de braço', 'polia', 2.5, false, 'reps', 1),
  (43, 'Rosca scott', 'bíceps', '{}'::grupo_muscular[], 'isolamento de braço', 'barra', 2.5, false, 'reps', 1),
  (44, 'Rack Pull', 'costas', array['posterior','glúteo']::grupo_muscular[], 'dominante de quadril', 'barra', 2.5, false, 'reps', 3),
  (45, 'Pull-over máquina', 'costas', '{}'::grupo_muscular[], 'isolamento de costas', 'máquina', 5.0, false, 'reps', 3),
  (46, 'Pullover com halter', 'costas', array['peito']::grupo_muscular[], 'isolamento de costas', 'halter', 2.0, false, 'reps', 2),
  (47, 'Pullover na polia alta', 'costas', '{}'::grupo_muscular[], 'isolamento de costas', 'polia', 2.5, false, 'reps', 2),
  (48, 'Remada Meadows', 'costas', array['bíceps']::grupo_muscular[], 'puxar horizontal', 'barra', 2.5, true, 'reps', 3),
  (49, 'Remada T-Bar', 'costas', array['bíceps']::grupo_muscular[], 'puxar horizontal', 'barra', 2.5, false, 'reps', 2),
  (50, 'Remada baixa na polia', 'costas', array['bíceps']::grupo_muscular[], 'puxar horizontal', 'polia', 2.5, false, 'reps', 1),
  (51, 'Remada cavalinho', 'costas', array['bíceps']::grupo_muscular[], 'puxar horizontal', 'barra', 2.5, false, 'reps', 3),
  (52, 'Remada curvada com barra', 'costas', array['bíceps']::grupo_muscular[], 'puxar horizontal', 'barra', 2.5, false, 'reps', 1),
  (53, 'Remada curvada pronada', 'costas', array['bíceps']::grupo_muscular[], 'puxar horizontal', 'barra', 2.5, false, 'reps', 2),
  (54, 'Remada máquina', 'costas', array['bíceps']::grupo_muscular[], 'puxar horizontal', 'máquina', 5.0, false, 'reps', 1),
  (55, 'Remada serrote com halter', 'costas', array['bíceps']::grupo_muscular[], 'puxar horizontal', 'halter', 2.0, true, 'reps', 1),
  (56, 'Remada unilateral na polia', 'costas', array['bíceps']::grupo_muscular[], 'puxar horizontal', 'polia', 2.5, true, 'reps', 2),
  (57, 'Barra fixa pronada', 'costas', array['bíceps']::grupo_muscular[], 'puxar vertical', 'peso corporal', null, false, 'reps', 1),
  (58, 'Barra fixa supinada', 'costas', array['bíceps']::grupo_muscular[], 'puxar vertical', 'peso corporal', null, false, 'reps', 2),
  (59, 'Pulldown unilateral', 'costas', array['bíceps']::grupo_muscular[], 'puxar vertical', 'polia', 2.5, true, 'reps', 2),
  (60, 'Puxada com pegada neutra', 'costas', array['bíceps']::grupo_muscular[], 'puxar vertical', 'polia', 2.5, false, 'reps', 2),
  (61, 'Puxada com triângulo', 'costas', array['bíceps']::grupo_muscular[], 'puxar vertical', 'polia', 2.5, false, 'reps', 1),
  (62, 'Puxada frontal na polia', 'costas', array['bíceps']::grupo_muscular[], 'puxar vertical', 'polia', 2.5, false, 'reps', 1),
  (63, 'Puxada supinada na polia', 'costas', array['bíceps']::grupo_muscular[], 'puxar vertical', 'polia', 2.5, false, 'reps', 2),
  (64, 'Cable Pull Through', 'glúteo', array['posterior']::grupo_muscular[], 'dominante de quadril', 'polia', 2.5, false, 'reps', 3),
  (65, 'Elevação pélvica com barra', 'glúteo', array['posterior']::grupo_muscular[], 'dominante de quadril', 'barra', 2.5, false, 'reps', 1),
  (66, 'Elevação pélvica na máquina', 'glúteo', array['posterior']::grupo_muscular[], 'dominante de quadril', 'máquina', 5.0, false, 'reps', 1),
  (67, 'Frog Pump', 'glúteo', array['posterior']::grupo_muscular[], 'dominante de quadril', 'halter', 2.0, false, 'reps', 3),
  (68, 'Hip Thrust unilateral', 'glúteo', array['posterior']::grupo_muscular[], 'dominante de quadril', 'halter', 2.0, true, 'reps', 2),
  (69, 'Ponte de glúteo', 'glúteo', array['posterior']::grupo_muscular[], 'dominante de quadril', 'peso corporal', null, false, 'reps', 1),
  (70, 'Reverse Hyper', 'glúteo', array['posterior']::grupo_muscular[], 'dominante de quadril', 'máquina', 5.0, false, 'reps', 3),
  (71, 'Coice na máquina', 'glúteo', '{}'::grupo_muscular[], 'isolamento de perna', 'máquina', 5.0, true, 'reps', 2),
  (72, 'Coice na polia', 'glúteo', '{}'::grupo_muscular[], 'isolamento de perna', 'polia', 2.5, true, 'reps', 1),
  (73, 'Bird Dog', 'lombar', array['abdômen']::grupo_muscular[], 'antiextensão', 'peso corporal', null, false, 'reps', 2),
  (74, 'Hiperextensão com anilha', 'lombar', array['glúteo','posterior']::grupo_muscular[], 'extensão de tronco', 'anilha', 2.5, false, 'reps', 2),
  (75, 'Hiperextensão lombar', 'lombar', array['glúteo','posterior']::grupo_muscular[], 'extensão de tronco', 'peso corporal', null, false, 'reps', 1),
  (76, 'Jefferson Curl', 'lombar', array['posterior']::grupo_muscular[], 'extensão de tronco', 'halter', 2.0, false, 'reps', 3),
  (77, 'Superman no solo', 'lombar', '{}'::grupo_muscular[], 'extensão de tronco', 'peso corporal', null, false, 'reps', 2),
  (78, 'Desenvolvimento Arnold', 'ombro', array['tríceps']::grupo_muscular[], 'empurrar vertical', 'halter', 2.0, false, 'reps', 2),
  (79, 'Desenvolvimento Smith', 'ombro', array['tríceps']::grupo_muscular[], 'empurrar vertical', 'máquina', 5.0, false, 'reps', 2),
  (80, 'Desenvolvimento com halteres', 'ombro', array['tríceps']::grupo_muscular[], 'empurrar vertical', 'halter', 2.0, false, 'reps', 1),
  (81, 'Desenvolvimento militar com barra', 'ombro', array['tríceps']::grupo_muscular[], 'empurrar vertical', 'barra', 2.5, false, 'reps', 1),
  (82, 'Desenvolvimento máquina', 'ombro', array['tríceps']::grupo_muscular[], 'empurrar vertical', 'máquina', 5.0, false, 'reps', 1),
  (83, 'Crucifixo inverso com halteres', 'ombro', array['costas']::grupo_muscular[], 'isolamento de ombro', 'halter', 2.0, false, 'reps', 1),
  (84, 'Crucifixo inverso na máquina', 'ombro', array['costas']::grupo_muscular[], 'isolamento de ombro', 'máquina', 5.0, false, 'reps', 1),
  (85, 'Crucifixo inverso polia', 'ombro', array['costas']::grupo_muscular[], 'isolamento de ombro', 'polia', 2.5, true, 'reps', 2),
  (86, 'Cuban Press', 'ombro', '{}'::grupo_muscular[], 'isolamento de ombro', 'halter', 2.0, false, 'reps', 3),
  (87, 'Elevação Y', 'ombro', '{}'::grupo_muscular[], 'isolamento de ombro', 'halter', 2.0, false, 'reps', 3),
  (88, 'Elevação frontal com anilha', 'ombro', '{}'::grupo_muscular[], 'isolamento de ombro', 'anilha', 2.5, false, 'reps', 2),
  (89, 'Elevação frontal com halteres', 'ombro', '{}'::grupo_muscular[], 'isolamento de ombro', 'halter', 2.0, false, 'reps', 1),
  (90, 'Elevação lateral com halteres', 'ombro', '{}'::grupo_muscular[], 'isolamento de ombro', 'halter', 2.0, false, 'reps', 1),
  (91, 'Elevação lateral na máquina', 'ombro', '{}'::grupo_muscular[], 'isolamento de ombro', 'máquina', 5.0, false, 'reps', 1),
  (92, 'Elevação lateral na polia', 'ombro', '{}'::grupo_muscular[], 'isolamento de ombro', 'polia', 2.5, true, 'reps', 2),
  (93, 'Encolhimento com barra', 'ombro', '{}'::grupo_muscular[], 'isolamento de ombro', 'barra', 2.5, false, 'reps', 2),
  (94, 'Encolhimento com halteres', 'ombro', '{}'::grupo_muscular[], 'isolamento de ombro', 'halter', 2.0, false, 'reps', 1),
  (95, 'Face pull na polia', 'ombro', array['costas']::grupo_muscular[], 'isolamento de ombro', 'polia', 2.5, false, 'reps', 1),
  (96, 'High Pull', 'ombro', array['costas']::grupo_muscular[], 'isolamento de ombro', 'barra', 2.5, false, 'reps', 3),
  (97, 'Remada alta com barra', 'ombro', array['costas']::grupo_muscular[], 'isolamento de ombro', 'barra', 2.5, false, 'reps', 1),
  (98, 'Donkey Calf Raise', 'panturrilha', '{}'::grupo_muscular[], 'panturrilha', 'máquina', 5.0, false, 'reps', 3),
  (99, 'Panturrilha Smith', 'panturrilha', '{}'::grupo_muscular[], 'panturrilha', 'máquina', 5.0, false, 'reps', 2),
  (100, 'Panturrilha em pé na máquina', 'panturrilha', '{}'::grupo_muscular[], 'panturrilha', 'máquina', 5.0, false, 'reps', 1),
  (101, 'Panturrilha no leg press', 'panturrilha', '{}'::grupo_muscular[], 'panturrilha', 'máquina', 5.0, false, 'reps', 2),
  (102, 'Panturrilha sentado na máquina', 'panturrilha', '{}'::grupo_muscular[], 'panturrilha', 'máquina', 5.0, false, 'reps', 1),
  (103, 'Panturrilha sentado unilateral', 'panturrilha', '{}'::grupo_muscular[], 'panturrilha', 'máquina', 5.0, true, 'reps', 2),
  (104, 'Panturrilha unilateral com halter', 'panturrilha', '{}'::grupo_muscular[], 'panturrilha', 'halter', 2.0, true, 'reps', 2),
  (105, 'Tibial Raise', 'panturrilha', '{}'::grupo_muscular[], 'panturrilha', 'peso corporal', null, false, 'reps', 3),
  (106, 'Chest Press convergente', 'peito', array['tríceps','ombro']::grupo_muscular[], 'empurrar horizontal', 'máquina', 5.0, false, 'reps', 2),
  (107, 'Flexão de braço', 'peito', array['tríceps','ombro']::grupo_muscular[], 'empurrar horizontal', 'peso corporal', null, false, 'reps', 1),
  (108, 'Paralelas', 'peito', array['tríceps']::grupo_muscular[], 'empurrar horizontal', 'peso corporal', null, false, 'reps', 2),
  (109, 'Supino declinado com barra', 'peito', array['tríceps']::grupo_muscular[], 'empurrar horizontal', 'barra', 2.5, false, 'reps', 2),
  (110, 'Supino inclinado com barra', 'peito', array['ombro','tríceps']::grupo_muscular[], 'empurrar horizontal', 'barra', 2.5, false, 'reps', 1),
  (111, 'Supino inclinado com halteres', 'peito', array['ombro','tríceps']::grupo_muscular[], 'empurrar horizontal', 'halter', 2.0, false, 'reps', 1),
  (112, 'Supino máquina', 'peito', array['tríceps','ombro']::grupo_muscular[], 'empurrar horizontal', 'máquina', 5.0, false, 'reps', 1),
  (113, 'Supino pegada neutra', 'peito', array['tríceps','ombro']::grupo_muscular[], 'empurrar horizontal', 'halter', 2.0, false, 'reps', 2),
  (114, 'Supino reto com barra', 'peito', array['tríceps','ombro']::grupo_muscular[], 'empurrar horizontal', 'barra', 2.5, false, 'reps', 1),
  (115, 'Supino reto com halteres', 'peito', array['tríceps','ombro']::grupo_muscular[], 'empurrar horizontal', 'halter', 2.0, false, 'reps', 1),
  (116, 'Crossover baixo para cima', 'peito', '{}'::grupo_muscular[], 'isolamento de peito', 'polia', 2.5, false, 'reps', 2),
  (117, 'Crossover cima para baixo', 'peito', '{}'::grupo_muscular[], 'isolamento de peito', 'polia', 2.5, false, 'reps', 2),
  (118, 'Crossover na polia', 'peito', '{}'::grupo_muscular[], 'isolamento de peito', 'polia', 2.5, false, 'reps', 1),
  (119, 'Crucifixo com halteres', 'peito', '{}'::grupo_muscular[], 'isolamento de peito', 'halter', 2.0, false, 'reps', 1),
  (120, 'Crucifixo inclinado com halteres', 'peito', '{}'::grupo_muscular[], 'isolamento de peito', 'halter', 2.0, false, 'reps', 2),
  (121, 'Svend Press', 'peito', '{}'::grupo_muscular[], 'isolamento de peito', 'anilha', 2.5, false, 'reps', 3),
  (122, 'Voador (peck deck)', 'peito', '{}'::grupo_muscular[], 'isolamento de peito', 'máquina', 5.0, false, 'reps', 1),
  (123, 'Bom dia com barra', 'posterior', array['glúteo','lombar']::grupo_muscular[], 'dominante de quadril', 'barra', 2.5, false, 'reps', 3),
  (124, 'Good Morning Smith', 'posterior', array['glúteo','lombar']::grupo_muscular[], 'dominante de quadril', 'máquina', 5.0, false, 'reps', 3),
  (125, 'Levantamento terra', 'posterior', array['glúteo','costas']::grupo_muscular[], 'dominante de quadril', 'barra', 2.5, false, 'reps', 1),
  (126, 'Levantamento terra romeno', 'posterior', array['glúteo']::grupo_muscular[], 'dominante de quadril', 'barra', 2.5, false, 'reps', 1),
  (127, 'Levantamento terra sumô', 'posterior', array['glúteo','quadríceps']::grupo_muscular[], 'dominante de quadril', 'barra', 2.5, false, 'reps', 3),
  (128, 'Stiff com halteres', 'posterior', array['glúteo']::grupo_muscular[], 'dominante de quadril', 'halter', 2.0, false, 'reps', 1),
  (129, 'Cadeira flexora', 'posterior', '{}'::grupo_muscular[], 'isolamento de perna', 'máquina', 5.0, false, 'reps', 1),
  (130, 'Flexora unilateral em pé', 'posterior', '{}'::grupo_muscular[], 'isolamento de perna', 'máquina', 5.0, true, 'reps', 2),
  (131, 'Glute Ham Raise', 'posterior', array['glúteo']::grupo_muscular[], 'isolamento de perna', 'peso corporal', null, false, 'reps', 3),
  (132, 'Mesa flexora', 'posterior', '{}'::grupo_muscular[], 'isolamento de perna', 'máquina', 5.0, false, 'reps', 1),
  (133, 'Nordic Curl', 'posterior', '{}'::grupo_muscular[], 'isolamento de perna', 'peso corporal', null, false, 'reps', 3),
  (134, 'Agachamento frontal', 'quadríceps', array['glúteo']::grupo_muscular[], 'dominante de joelho', 'barra', 2.5, false, 'reps', 2),
  (135, 'Agachamento goblet', 'quadríceps', array['glúteo']::grupo_muscular[], 'dominante de joelho', 'halter', 2.0, false, 'reps', 1),
  (136, 'Agachamento livre', 'quadríceps', array['glúteo','posterior']::grupo_muscular[], 'dominante de joelho', 'barra', 2.5, false, 'reps', 1),
  (137, 'Agachamento no Smith', 'quadríceps', array['glúteo']::grupo_muscular[], 'dominante de joelho', 'máquina', 5.0, false, 'reps', 1),
  (138, 'Agachamento sumô com halter', 'quadríceps', array['glúteo']::grupo_muscular[], 'dominante de joelho', 'halter', 2.0, false, 'reps', 2),
  (139, 'Belt Squat', 'quadríceps', array['glúteo']::grupo_muscular[], 'dominante de joelho', 'máquina', 5.0, false, 'reps', 3),
  (140, 'Hack machine', 'quadríceps', array['glúteo']::grupo_muscular[], 'dominante de joelho', 'máquina', 5.0, false, 'reps', 1),
  (141, 'Landmine Squat', 'quadríceps', array['glúteo']::grupo_muscular[], 'dominante de joelho', 'barra', 2.5, false, 'reps', 3),
  (142, 'Leg press 45', 'quadríceps', array['glúteo']::grupo_muscular[], 'dominante de joelho', 'máquina', 5.0, false, 'reps', 1),
  (143, 'Sissy Squat', 'quadríceps', '{}'::grupo_muscular[], 'dominante de joelho', 'peso corporal', null, false, 'reps', 3),
  (144, 'Spanish Squat', 'quadríceps', '{}'::grupo_muscular[], 'dominante de joelho', 'peso corporal', null, false, 'reps', 3),
  (145, 'Cadeira extensora', 'quadríceps', '{}'::grupo_muscular[], 'isolamento de perna', 'máquina', 5.0, false, 'reps', 1),
  (146, 'Extensora unilateral', 'quadríceps', '{}'::grupo_muscular[], 'isolamento de perna', 'máquina', 5.0, true, 'reps', 2),
  (147, 'Afundo com halteres', 'quadríceps', array['glúteo']::grupo_muscular[], 'unilateral', 'halter', 2.0, true, 'reps', 1),
  (148, 'Agachamento búlgaro', 'quadríceps', array['glúteo']::grupo_muscular[], 'unilateral', 'halter', 2.0, true, 'reps', 2),
  (149, 'Avanço no Smith', 'quadríceps', array['glúteo']::grupo_muscular[], 'unilateral', 'máquina', 5.0, true, 'reps', 2),
  (150, 'Passada', 'quadríceps', array['glúteo']::grupo_muscular[], 'unilateral', 'halter', 2.0, true, 'reps', 2),
  (151, 'Step-up no banco', 'quadríceps', array['glúteo']::grupo_muscular[], 'unilateral', 'halter', 2.0, true, 'reps', 2),
  (152, 'Supino fechado', 'tríceps', array['peito']::grupo_muscular[], 'empurrar horizontal', 'barra', 2.5, false, 'reps', 2),
  (153, 'Extensão acima cabeça polia', 'tríceps', '{}'::grupo_muscular[], 'isolamento de braço', 'polia', 2.5, false, 'reps', 2),
  (154, 'JM Press', 'tríceps', array['peito']::grupo_muscular[], 'isolamento de braço', 'barra', 2.5, false, 'reps', 3),
  (155, 'Kickback polia', 'tríceps', '{}'::grupo_muscular[], 'isolamento de braço', 'polia', 2.5, true, 'reps', 2),
  (156, 'Mergulho no banco', 'tríceps', '{}'::grupo_muscular[], 'isolamento de braço', 'peso corporal', null, false, 'reps', 2),
  (157, 'Tríceps coice', 'tríceps', '{}'::grupo_muscular[], 'isolamento de braço', 'halter', 2.0, true, 'reps', 2),
  (158, 'Tríceps francês com halter', 'tríceps', '{}'::grupo_muscular[], 'isolamento de braço', 'halter', 2.0, false, 'reps', 2),
  (159, 'Tríceps máquina', 'tríceps', '{}'::grupo_muscular[], 'isolamento de braço', 'máquina', 5.0, false, 'reps', 2),
  (160, 'Tríceps na polia com barra', 'tríceps', '{}'::grupo_muscular[], 'isolamento de braço', 'polia', 2.5, false, 'reps', 1),
  (161, 'Tríceps na polia com corda', 'tríceps', '{}'::grupo_muscular[], 'isolamento de braço', 'polia', 2.5, false, 'reps', 1),
  (162, 'Tríceps testa com barra W', 'tríceps', '{}'::grupo_muscular[], 'isolamento de braço', 'barra', 2.5, false, 'reps', 1),
  (163, 'Tríceps unilateral polia', 'tríceps', '{}'::grupo_muscular[], 'isolamento de braço', 'polia', 2.5, true, 'reps', 2)
on conflict (id) do update set
  nome               = excluded.nome,
  grupo_primario     = excluded.grupo_primario,
  grupos_secundarios = excluded.grupos_secundarios,
  padrao_movimento   = excluded.padrao_movimento,
  equipamento        = excluded.equipamento,
  incremento_kg      = excluded.incremento_kg,
  unilateral         = excluded.unilateral,
  medida             = excluded.medida,
  comum              = excluded.comum;

-- O catálogo usa id serial, mas o seed traz ids explícitos. Sem isto o
-- próximo insert sem id colide na primary key.
select setval(
  pg_get_serial_sequence('public.exercicios', 'id'),
  (select max(id) from public.exercicios)
);
